<h1><?php echo Yii::t('guia','Playas')?></h1> 
<p><?php echo Yii::t('guia','intro playas Elche')?></p>
<p><iframe width="560" height="315" src="http://www.youtube.com/embed/g4PBYTdtfLs" frameborder="0" allowfullscreen></iframe></p>
<p><?php echo Yii::t('guia','intro playas Elche 2')?></p>
<h2>Arenales del Sol</h2> 
<p><?php echo Yii::t('guia','intro arenales')?></p>
<img src="images/arenales-del-sol-001.jpg" width="185" height ="123px"> 
<p><?php echo Yii::t('guia','intro arenales')?></p>
<h2>Santa Pola</h2> 
<h3> Gran Playa </h3> 
<p> <img src="images/playabierta.gif" alt="Playa Abierta" title="Playa Abierta"> <img src="images/playasemiurb.gif" alt="Playa Semi Urbana" title="Playa Semi Urbana"> <img src="images/estadomar.gif" alt="Estado del Mar" title="Estado del Mar"> <img src="images/pasarelas.gif" alt="Pasarelas" title="Pasarelas"> <img src="images/accminus.gif" alt="Acceso Persona Movilidad Reducida" title="Acceso Persona Movilidad Reducida"> <img src="images/restaurante.gif" alt="Restaurante" title="Restaurante"> <img src="images/lavapie.gif" alt="Lavapies" title="Lavapies"> <img src="images/chiringuito.gif" alt="Chiringuito" title="Chiringuito"> <img src="images/cruzroja.gif" alt="Cruz Roja" title="Cruz Roja"> <img src="images/serviwc.gif" alt="Servicios WC" title="Servicios WC"> <img src="images/deporti.gif" alt="Juegos Deportivos" title="Juegos Deportivos"> <img src="images/infotur.gif" alt="Tourist Info" title="Tourist Info"> <img src="images/parking.gif" alt="Parking" title="Parking"> <img src="images/windsurf.gif" alt="Windsurf" title="Windsurf"> <img src="images/patines.gif" alt="Patines" title="Patines"> <img src="images/accesible.gif" alt="Accesible" title="Accesible"> </p> 
<img src="images/santapola1.jpg" width="185px" height="123px"> <img src="images/santapola2.jpg" width="185px" height="123px"> 
<p><?php echo Yii::t('guia','intro Gran Playa')?>
<a href="http://www.comunitatvalenciana.com/playa/costa-blanca-santa-pola-gran-playa-0" target="_blank"><?php echo Yii::t('guia','Mas Info')?></a> </p>
<h3> Playa Levante</h3> 
<p><img src="images/playabierta.gif" alt="Playa Abierta" title="Playa Abierta"> <img src="images/estadomar.gif" alt="Estado del Mar" title="Estado del Mar"> <img src="images/pasarelas.gif" alt="Pasarelas" title="Pasarelas"> <img src="images/accminus.gif" alt="Acceso Persona Movilidad Reducida" title="Acceso Persona Movilidad Reducida"> <img src="images/restaurante.gif" alt="Restaurante" title="Restaurante"> <img src="images/lavapie.gif" alt="Lavapies" title="Lavapies"> <img src="images/chiringuito.gif" alt="Chiringuito" title="Chiringuito"> <img src="images/cruzroja.gif" alt="Cruz Roja" title="Cruz Roja"> <img src="images/serviwc.gif" alt="Servicios WC" title="Servicios WC"> <img src="images/deporti.gif" alt="Juegos Deportivos" title="Juegos Deportivos"> <img src="images/playaurban.gif" alt="Playa Urbana" title="Playa Urbana"> <img src="images/hoteles.gif" alt="Hoteles" title="Hoteles"> <img src="images/parking.gif" alt="Parking" title="Parking"> <img src="images/patines.gif" alt="Patines" title="Patines"> <img src="images/accesible.gif" alt="Accesible" title="Accesible"> <img src="images/bandera_azul.gif" alt="Bandera Azul" title="Bandera Azul"></p> 
<img src="images/santapola3.jpg" width="185px" height="123px"> <img src="images/santapola6.jpg" width="185px" height="123px"> 
<p><?php echo Yii::t('guia','intro Playa Levante')?>
<a href="http://www.comunitatvalenciana.com/playa/costa-blanca-santa-pola-playa-llevant-0" target="_blank"><?php echo Yii::t('guia','Mas Info')?></a> </p>
<h3> Calas </h3> 
<p> <img src="images/cala.gif" alt="Cala" title="Cala"> <img src="images/chiringuito.gif" alt="Chiringuito" title="Chiringuito"> <img src="images/playavirgen.gif" alt="Playa Virgen" title="Playa Virgen"> <img src="images/motoagua.gif" alt="Moto de Agua" title="Moto de Agua"> </p> 
<img src="images/cabo_aljup.jpg"> <img src="images/cala1.jpg" width="185px" height="123px"> <img src="images/cala2.jpg" width="185px" height="123px"> 
<p><?php echo Yii::t('guia','intro Calas Santa Pola')?>
<a href="http://www.comunitatvalenciana.com/playa/costa-blanca-santa-pola-calas-santa-pola-del-este-0" target="_blank"><?php echo Yii::t('guia','Mas Info')?></a></p>
<h3> Playa Varadero </h3> <p> 
<img src="images/playabierta.gif" alt="Playa Abierta" title="Playa Abierta"> <img src="images/playasemiurb.gif" alt="Playa Semi Urbana" title="Playa Semi Urbana"> <img src="images/pasarelas.gif" alt="Pasarelas" title="Pasarelas"> <img src="images/accminus.gif" alt="Acceso Persona Movilidad Reducida" title="Acceso Persona Movilidad Reducida"> <img src="images/restaurante.gif" alt="Restaurante" title="Restaurante"> <img src="images/lavapie.gif" alt="Lavapies" title="Lavapies"> <img src="images/chiringuito.gif" alt="Chiringuito" title="Chiringuito"> <img src="images/cruzroja.gif" alt="Cruz Roja" title="Cruz Roja"> <img src="images/serviwc.gif" alt="Servicios WC" title="Servicios WC"> <img src="images/deporti.gif" alt="Juegos Deportivos" title="Juegos Deportivos"> <img src="images/infotur.gif" alt="Tourist Info" title="Tourist Info"> <img src="images/parking.gif" alt="Parking" title="Parking"> <img src="images/patines.gif" alt="Patines" title="Patines"> <img src="images/bandera_azul.gif" alt="Bandera Azul" title="Bandera Azul"> </p> 
<img src="images/santapola4.jpg" width="185px" height="123px"> <img src="images/santapola5.jpg" width="185px" height="123px"> 
<p><?php echo Yii::t('guia','intro Varadero')?>
<a href="http://www.comunitatvalenciana.com/playa/costa-blanca-santa-pola-playa-varadero-0" target="_blank"><?php echo Yii::t('guia','Mas Info')?></a></p>
<h3>Playa Tamarit </h3> 
<p> <img src="images/deporti.gif" alt="Juegos Deportivos" title="Juegos Deportivos"> <img src="images/playabierta.gif" alt="Playa Abierta" title="Playa Abierta"> <img src="images/pasarelas.gif" alt="Pasarelas" title="Pasarelas"> <img src="images/accminus.gif" alt="Acceso Persona Movilidad Reducida" title="Acceso Persona Movilidad Reducida"> <img src="images/restaurante.gif" alt="Restaurante" title="Restaurante"> <img src="images/vela.gif" alt="Vela" title="Vela"> <img src="images/chiringuito.gif" alt="Chiringuito" title="Chiringuito"> <img src="images/cruzroja.gif" alt="Cruz Roja" title="Cruz Roja"> <img src="images/serviwc.gif" alt="Servicios WC" title="Servicios WC"> <img src="images/deporti.gif" alt="Juegos Deportivos" title="Juegos Deportivos"> <img src="images/playaurban.gif" alt="Playa Urbana" title="Playa Urbana"> <img src="images/parking.gif" alt="Parking" title="Parking"> <img src="images/patines.gif" alt="Patines" title="Patines"> <img src="images/accesible.gif" alt="Accesible" title="Accesible"> <img src="images/bandera_azul.gif" alt="Bandera Azul" title="Bandera Azul"> </p> 
<img src="images/santapola7.jpg" width="185px" height="123px"> <img src="images/santapola8.jpg" width="185px" height="123px">
<p><?php echo Yii::t('guia','intro Tamarit')?>
<a href="http://www.comunitatvalenciana.com/playa/costa-blanca-santa-pola-playa-tamarit-0" target="_blank"><?php echo Yii::t('guia','Mas Info')?></a></p>
<h2>La Marina</h2> 
<img src="images/lamarina1.jpg" width="185px" height="123px"> <img src="images/lamarina2.jpg" width="185px" height="123px">
<p><?php echo Yii::t('guia','intro La Marina')?>
<p class="leyenda"> <img src="images/windsurf.gif" alt="Windsurf" title="Windsurf"/> <img src="images/parking.gif" alt="Parking" title="Parking"/> <img src="images/hoteles.gif" alt="Hoteles" title="Hoteles"/> <img src="images/infotur.gif" alt="Tourist Info" title="Tourist Info"/> <img src="images/deporti.gif" alt="Juegos Deportivos" title="Juegos Deportivos"/> <img src="images/serviwc.gif" alt="Servicios WC" title="Servicios WC"/> <img src="images/playavirgen.gif" alt="Playa Virgen" title="Playa Virgen"/> <img src="images/lavapie.gif" alt="Lavapies" title="Lavapies"/> <img src="images/vela.gif" alt="Vela" title="Vela"/> <img src="images/restaurante.gif" alt="Restaurante" title="Restaurante"/> <img src="images/accminus.gif" alt="Acceso Persona Movilidad Reducida" title="Acceso Persona Movilidad Reducida"/> <img src="images/camping.gif" alt="Camping" title="Camping"/> <img src="images/pasarelas.gif" alt="Pasarelas" title="Pasarelas"/> <img src="images/estadomar.gif" alt="Estado del Mar" title="Estado del Mar"/> <img src="images/playabierta.gif" alt="Playa Abierta" title="Playa Abierta"/> <img src="images/bandera_azul.gif" alt="Bandera Azul" title="Bandera Azul"/> </p>
<a href="http://www.comunitatvalenciana.com/playa/costa-blanca-elx/elche-playa-la-marina-0" target="_blank"><?php echo Yii::t('guia','Mas Info')?></a> </p>
	  